#!/bin/bash
# set WITH_COLORS to 2 for plain text (without colors)
WITH_COLORS=2
# set the language to english for english .log file
LANG=en_EN.UTF-8
#
make clean
#
# The "big three" standard bootloaders.
# These need to be built AFTER the platforms, or they'll get renamed
echo " "; echo "***** make atmega8_autoBaud_LED_On ******"
make atmega8  LED_START_FLASHES=4 BAUD_RATE=36
mv optiboot_atmega8.lst optiboot_m8_autoBaud_LED_On.lst
mv optiboot_atmega8.hex optiboot_m8_autoBaud_LED_On.hex
mv optiboot_atmega8.log optiboot_m8_autoBaud_LED_On.log
echo " "; echo "***** make atmega8 ******"
make atmega8 

echo " "; echo "***** make atmega168_autoBaud_LED_On ******"
make atmega168 LED_START_FLASHES=0 BAUD_RATE=36
mv optiboot_atmega168.lst optiboot_m168_autoBaud_LED_On.lst
mv optiboot_atmega168.hex optiboot_m168_autoBaud_LED_On.hex
mv optiboot_atmega168.log optiboot_m168_autoBaud_LED_On.log
echo " "; echo "***** make atmega168 ******"
make atmega168 

echo " "; echo "***** make atmega328 ******"
make atmega328

echo " "; echo "***** make atmega328p_autoBaud_LED_on ******"
make atmega328p LED_START_FLASHES=0 LED_DATA_FLASH=0 BAUD_RATE=36
mv optiboot_atmega328p.lst optiboot_m328p_autoBaud_LED_On.lst
mv optiboot_atmega328p.hex optiboot_m328p_autoBaud_LED_On.hex
mv optiboot_atmega328p.log optiboot_m328p_autoBaud_LED_On.log
echo " "; echo "***** make atmega328p ******"
make atmega328p 
#
make steril


