#!/bin/bash

# show_help3.sh shows help text part 3 for optiboot

source ./def_colors.sh
MYLANG=`echo ${LANGUAGE} | cut -c 1-3`
echo " "
if [ "${MYLANG}" == "de_" ] ; then
 echo "Weitere Optionen zum Erzeugen eines optiboot Bootloaders (${Vgreen}make help3${Vnormal}):"
 echo " "
 echo "${Vgelb}SOFT_UART${Vnormal}       wählt ein Software Programm anstelle des Hardware UART."
 echo " "
 echo "${Vgelb}UART_RX${Vnormal}         Wählt einen Pin und Port für den Software UART Eingang."
 echo " "
 echo "${Vgelb}UART_TX${Vnormal}         Wählt einen Pin und Port für den Software UART Ausgang."
 echo " "
 echo "${Vgelb}C_SOURCE${Vnormal}        =1 wählt die C-Quellen anstelle der Assemblerversion."
 echo " "
 echo "${Vgelb}BIGBOOT${Vnormal}         wählt die angegebene Menge zusätzlichen Speicher für optiboot."
 echo "                Die Option wird nur für Tests der Längenanpassung sinnvoll."
 echo " "
 echo "${Vgelb}VIRTUAL_BOOT_PARTITION${Vnormal} ändert zwei Interrupt Vektoren des Anwenderprogramms,"
 echo "                um einen Bootloader auch ohne die Bootloader Unterstützung des"
 echo "                AVR Prozessor (ATtiny) zu ermöglichen."
 echo " "
 echo "${Vgelb}TIMEOUT_MS${Vnormal}      gibt eine Zeitobergrenze in ms für das Warten auf serielle"
 echo "                Daten an. Nach dieser Zeit wird das Anwenderprogramm gestartet."
 echo " "
 echo "${Vgelb}OSCCAL_CORR${Vnormal}     gibt einen Korrekturwert für das OSCCAL-Byte des internen"
 echo "                RC-Oszillators an."
 echo " "
 echo "${Vgelb}FORCE_RSTDISBL${Vnormal}  läßt das Setzen des RSTDISBL Fuse-Bits zu, wenn auf 1 gesetzt."
 echo "                Ohne diese Option wird die Erzeugung des Bootloaders abgebrochen."
 echo " "
 echo "${Vgelb}NO_EARLY_PAGE_ERASE${Vnormal} verhindert das Löschen der Flash-Speicherseite während"
 echo "                des Datenempfang. Das nach dem Datenempfang durchgeführte"
 echo "                Löschen macht den Programmiervorgang etwa 30% langsamer,"
 echo "                spart aber 14 Byte Platz für den optiboot."
 echo " "
else
 echo "Additional options for building a optiboot (${Vgreen}make help3${Vnormal}):"
 echo "${Vgelb}SOFT_UART${Vnormal}      select a software UART solution instead of the hardware UART."
 echo " "
 echo "${Vgelb}UART_RX${Vnormal}        specifies the port and pin for software UART input."
 echo " "
 echo "${Vgelb}UART_TX${Vnormal}        specifies the port and pin for software UART output."
 echo " "
 echo "${Vgelb}C_SOURCE${Vnormal}       set to 1 for C source instead of assembler version."
 echo " "
 echo "${Vgelb}INVERSE_UART${Vnormal}   set to 1 for inverting the level of RX and TX signals, only"
 echo "               with SOFT_UART possible."
 echo " "
 echo "${Vgelb}BIGBOOT${Vnormal}        select additional memory for the bootloader to test"
 echo "               the automatic selection of start address and the number"
 echo "               of boot pages."
 echo " "
 echo "${Vgelb}VIRTUAL_BOOT_PARTITION${Vnormal} changes two interrupt vector jmp addresses"
 echo "               for starting the bootloader with the reset vector."
 echo " "
 echo "${Vgelb}TIMEOUT_MS${Vnormal}     select a time limit for receiving boot data in ms units."
 echo " "
 echo "${Vgelb}OSCCAL_CORR${Vnormal}    specifies a correction value for the OSCCAL Byte for the"
 echo "               internal RC clock generator."
 echo " "
 echo "${Vgelb}FORCE_RSTDISBL${Vnormal} enables setting of the RSTDISBL bit to 0."
 echo "               Otherwise compiling is aborted."
 echo " "
 echo "${Vgelb}NO_EARLY_PAGE_ERASE${Vnormal} will disable the early page erase before data fetch."
 echo "              So the programming of flash is about 30% slower,"
 echo "              but this option will save 14 bytes optiboot space."
 echo " "
fi
