#!/bin/bash

# show_help2.sh shows help text part 1 for optiboot

source ./def_colors.sh
MYLANG=`echo ${LANGUAGE} | cut -c 1-3`
if [ "${MYLANG}" == "de_" ] ; then
 echo " "
 echo "Das ist der Hilfetext für die optiboot Makefile (${Vgreen}make help2${Vnormal})"
 echo "Wichtige Optionen für die Erzeugung eines optiboot bootloaders:"
 echo  "${Vgelb}AVR_FREQ${Vnormal}       gibt die Arbeitsfrequenz (Hz) für den AVR an."
 echo " "
 echo "${Vgelb}BAUD_RATE${Vnormal}      gibt die gewünschte Baudrate für die serielle Schnittstelle an."
 echo "               Ein Wert unter 100 wählt eine automatische Baudraten-Anpassung."
 echo "               Dabei wird bei Werten von 40-59 nur eine Zeitüberwachung"
 echo "               durchgeführt, bei Werten unter 40 wird nichts kontrolliert."
 echo "               Bei Werten von 60-99 wird das empfangene Zeichen aufwendiger"
 echo "               kontrolliert."
 echo " "
 echo "${Vgelb}UART${Vnormal}           gibt die Nummer des Hardware UART (0-3) an, wenn vorhanden."
 echo " "
 echo "${Vgelb}LED_START_FLASHES${Vnormal} gibt die Anzahl des Blinkens einer LED an."
 echo "               Eine 0 wählt die Funktion ab, bei 1 wird nur einmal geblinkt."
 echo "               Bei negative Zahlen wird das Blinken NICHT vorzeitig verlassen,"
 echo "               wenn ein ankommendes Zeichen auf der seriellen Schnittstelle"
 echo "               erkannt wird."
 echo " "
 echo "${Vgelb}LED_DATA_FLASH =1${Vnormal} lässt die LED aufleuchten, wenn auf serielle Daten gewartet wird. "
 echo "               =4 Schaltet die LED nur beim Start ein."
 echo " "
 echo "${Vgelb}LED${Vnormal}            spezifiziert den Port und das Bit, wo die LED angeschlossen ist."
 echo "               LED=B5 würde das Bit 5 von Port B wählen."
 echo " "
 echo "${Vgelb}SUPPORT_EEPROM${Vnormal} ermöglicht das Beschreiben des EEproms mit dem bootloader,"
 echo "               wenn ungleich 0 gesetzt wird. In der Assemblerversion ist"
 echo "               auch ohne Angabe der Option das EEprom Beschreiben ermöglicht."
 echo " "
 echo "${Vgelb}ISP${Vnormal}            mit dieser Option wird für die ISP Schnittstelle avrdude gestartet"
 echo "               ISP=1 startet das Beschreiben des AVR mit dem optiboot Bootloader."
 echo "               ISP=2 statet eine extra Kontrolle des vorhandenen Bootloaders (verify)."
 echo "               ISP=3 liest den kompletten Flash Speicher des AVR (Read_<AVR-ID>.hex)."
 echo "               ISP=4 liest das komplette EEprom des AVR (Read_<AVR_ID>.eep."
 echo " "
 echo "${Vgelb}NO_APP_SPM${Vnormal}     verhindert den Anwenderaufruf zu do_spm wenn auf 1 gesetzt."
 echo "               Das Setzen auf 2 wird allen Spezialcode entfernen (4 Bytes kleiner als =1)"
 echo " "
 echo "Bei jedem make Aufruf muß der Ziel-AVR-Prozessor <AVR_ID> angegeben werden,"
 echo "um einen passenden optiboot bootloader mit den zusätzlich gewählten Optionen"
 echo "zu generieren."
 echo "Beispiel:"
 echo "${Vgreen}make atmega328p LED_START_FLASHES=0 LED_DATA_FLASH=1${Vnormal}"
 echo "würde einen optiboot generieren ohne das LED-Blinken mit aufleuchtender LED,"
 echo "wenn auf RX Daten gewartet wird."
 echo "Mit ${Vgreen}make help3${Vnormal} werden weitere Optionen aufgelistet."
 echo "${Vgreen}make pl${Vnormal}   listet die unterstützten AVR-Prozessoren."
 echo " "

else
 echo "This is the build in help text for the optiboot Makefile (${Vgreen}make help2${Vnormal})"
 echo "Important options to build optiboot:"
 echo "${Vgelb}AVR_FREQ${Vnormal}       specifies the operating frequency (Hz) of the target AVR."
 echo " "
 echo "${Vgelb}BAUD_RATE${Vnormal}      specifies the baud rate of the serial interface."
 echo "               A value less than 100 select the baud rate measurement,"
 echo "               less than 60 with a simpler method and less than 40"
 echo "               additionally without a time limit."
 echo " "
 echo "${Vgelb}UART${Vnormal}           specifies the hardware UART number (0-3 if existing)."
 echo " "
 echo "${Vgelb}LED_START_FLASHES${Vnormal} specifies the number of times to flicker the LED"
 echo "               before the serial communication starts. 0 means no flicker."
 echo " "
 echo "${Vgelb}LED_DATA_FLASH${Vnormal} let the LED light during serial character input wait."
 echo " "
 echo "${Vgelb}LED${Vnormal}            specifies with two characters the port and bit number."
 echo "               LED=B5 will select bit 5 of port B."
 echo " "
 echo "${Vgelb}SUPPORT_EEPROM${Vnormal} select the EEprom support, if set to nonzero value"
 echo " "
 echo "${Vgelb}ISP${Vnormal}            will start avrdude for download of optiboot if set to 1."
 echo "               2 will start a verify with avrdude,"
 echo "               3 will read the complete flash to Read_<AVR-ID>.hex,"
 echo "               4 will read the complete EEprom to Read_<AVR-ID>.eep."
 echo " "
 echo "${Vgelb}NO_APP_SPM${Vnormal}     disallow application call to do_spm if set to 1."
 echo "               setting to 2 will remove all the special code (4 Bytes smaller as =1)"
 echo " "
 echo "You must allways specify a target AVR processor (AVR-ID) to build"
 echo "a proper optiboot bootloader with any of the available options."
 echo " "
 echo "Example:"
 echo "${Vgreen}make atmega328p${} LED_START_FLASHES=0 LED_DATA_FLASH=1"
 echo "would deselect the blinking LED at the bootloader start and"
 echo "would use a bright LED when waiting for Rx data."
 echo "Type ${Vgreen}make help3${} for additional options!"
 echo "${Vgreen}make pl${}   list the names of the supported AVR processors."
 echo " "
fi
